Interactive plugin
gatling/gatling-enterprise-plugin-commons pull request #30
Opened 2021-12-23 17:01 UTC by tpetillot

**Motivation:**
We need an interactive mode, so the user won't have to fill any fields

**Modifications:**
* Separe HTTP client from class defining plugin interactions
  (EnterprisePlugin)
* Add InteractiveEnterprisePlugin and its implementation for
  interactivity
* Rework package tree

**ref:** MISC-314

2022-01-03 10:04 UTC, ccedric requested changes

2022-01-03 10:04 UTC, ccedric commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +        int read = scanner.readInt();
Please keep a "scanner.nextLine" here, as "nextInt" doesn't work the same way: it doesn't consume EOL

2022-01-03 10:04 UTC, ccedric commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +
remove empty line

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/EnterprisePluginClient.java
> +   */
No need to duplicate Javadoc in the implementation if present in the interface.

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePlugin.java
> + * input
```suggestion
 * Enterprise plugin features that require inputs from the user, each method may block awaiting for user
 * input.
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePlugin.java
> + * <p>Method can throw {@link EmptyChoicesException} when API return an empty set of choice.
```suggestion
 * <p>All methods can throw an {@link EmptyChoicesException} if the API returns an empty set of available choices.
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePlugin.java
> +   * @param file Required, Path to the packaged JAR file to upload and run
```suggestion
   * @param teamId Optional, if not null and the team exists, will be automatically pick
   * @param groupId Optional, if not null, will prefix the proposed package name
   * @param artifactId Optional, if not null, will suffix the proposed package name
   * @param className Optional, if not null, will be added to the list of available classNames
   * @param classNames Required, the list of potential Simulation class names in the project
   * @param systemProperties Required, can be an empty map; override system properties when running the simulation
   * @param file Required, path to the packaged JAR file to upload and run
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePlugin.java
> +   * @param className Optional, if not null, will be added in the list of available classNames
Why would it be _added_ to the available classes? Available classes are the ones detected in the actual project classes (setting another class name will never work); this should automatically choose the class name if it is present in the list of detected class names (similar to specifying `teamId` for the team).

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +  private static final int EXCLUDED_MAX_POOL_SIZE = 10;
"exclusive", rather than "excluded", maximum.

Also:
- any reason to set the actual max value to 9? Seems a bit weird.
- Should we really have a max value _on the client side_?

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +    logger.info("Do you want to create or start a simulation?");
```suggestion
    logger.info("Do you want to create a new simulation or start an existing one?");
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +      logger.info(String.format("Pick only available simulation %s", simulation.show()));
```suggestion
      logger.info(String.format("Picking the only available simulation: %s", simulation.show()));
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +    logger.info("Please, choose the className of your simulation");
```suggestion
    logger.info("Choose the class name for your simulation");
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +      logger.info("Please, choose your package name");
```suggestion
      logger.info("Choose a package name");
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +      logger.info("Please, enter your package name");
```suggestion
      logger.info("Enter a package name");
```

2022-01-03 10:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/client/http/OkHttpEnterpriseClient.java
> +      throw new IllegalStateException("Checksum algorithm was not available", e);
it's a checked exception, but we don't really expect it to ever happen for the MD5 algorithm, so I'd say this makes sense (though it could be done directly inside `PkgChecksum.computeChecksum`).

2022-01-03 13:06 UTC, tpetillot commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +      logger.info(String.format("Pick only available simulation %s", simulation.show()));
It's a further log, here, it's not about starting but choosing/picking.

2022-01-03 13:11 UTC, tpetillot commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +        int read = scanner.readInt();
It's not java scanner anymore.

2022-01-03 13:17 UTC, slandelle requested changes

2022-01-03 13:17 UTC, slandelle commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +      logger.info(String.format("Pick only available simulation %s", simulation.show()));
This looks super overkill to me => `"Pick only available simulation " + simulation.show()`

2022-01-03 13:20 UTC, tpetillot commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePlugin.java
> +   * @param className Optional, if not null, will be added in the list of available classNames
Kept same behavior as previous implementation on this, but I agree with your suggestion, will update.

2022-01-03 13:23 UTC, tpetillot commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +  private static final int EXCLUDED_MAX_POOL_SIZE = 10;
Agreed, set the limit to 100 to avoid bad inputs.

2022-01-03 14:00 UTC, slandelle commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +            throw new ValidationException(
That's typically an IllegalArgumentException

2022-01-03 14:00 UTC, slandelle commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +      simulationNames.add(simulationNameFromClassName(className));
java.util.Collections.singletonSet

2022-01-03 14:02 UTC, slandelle commented on src/main/java/io/gatling/plugin/io/PluginLogger.java
> +  void success(String message);
`success`??? What's the difference with `info`? Moreover, it seems unused.

2022-01-03 14:08 UTC, slandelle commented on src/main/java/io/gatling/plugin/util/show/Showable.java
> +public interface Showable {
What is this for?

2022-01-03 14:15 UTC, tpetillot commented on src/main/java/io/gatling/plugin/EnterprisePluginClient.java
> +import io.gatling.plugin.model.Package;
Package exist in `java.lang`, should we go with Pkg?

2022-01-03 14:15 UTC, tpetillot commented on src/main/java/io/gatling/plugin/EmptyChoicesException.java
> +public class EmptyChoicesException extends Exception {
> Should it extend from IllegalArgumentException or IllegalStateException instead?

I don't think so, we wan't callers of interactive `createAndStart` to be aware of this exception

2022-01-03 14:19 UTC, slandelle commented on src/main/java/io/gatling/plugin/EnterprisePluginClient.java
> +import io.gatling.plugin.model.Package;
Agree. I considered also reporting this one.

2022-01-03 14:44 UTC, tpetillot commented on src/main/java/io/gatling/plugin/util/show/ShowableString.java
> +public final class ShowableString implements Showable {
A string is not an instance of Showable, it was not possible to benefits from `InputChoice` methods.

2022-01-03 14:46 UTC, ccedric commented on src/main/java/io/gatling/plugin/EnterprisePlugin.java
>    void checkVersionSupport(String client, String version) throws EnterpriseClientException;
The annoying thing is that `checkVersionSupport` is only in the non-interactive EnterprisePlugin, so we need to instantiate an EnterprisePlugin to call it, even if we are in an interactive step.

2022-01-03 14:52 UTC, tpetillot commented on src/main/java/io/gatling/plugin/util/show/Showable.java
> +public interface Showable {
Used by `InputChoice` to display choices from a list of classes that extend Showable. Should we prefer to pass a `E -> String`

2022-01-03 15:04 UTC, ccedric commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +          logger.error(String.format("%d is not between %d and %d", read, 0, excludedMax));
it should be excludedMax -1

2022-01-03 15:18 UTC, ccedric commented on src/main/java/io/gatling/plugin/InteractiveEnterprisePluginClient.java
> +  private static final int EXCLUSIVE_MAX_POOL_SIZE = 100;
It should be 10

2022-01-03 15:32 UTC, ccedric commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +      String read = scanner.readString();
We should check that the String here is not empty (it is done afterwards for the package, but not for the simulation)

2022-01-03 15:32 UTC, ccedric commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +          logger.error(String.format("%d is not between %d and %d", read, 0, excludedMax));
We should not allow the 0 value, it does not make any sense to start 0 injector for example

2022-01-03 16:22 UTC, tpetillot commented on src/main/java/io/gatling/plugin/io/input/InputChoice.java
> +          logger.error(String.format("%d is not between %d and %d", read, 0, excludedMax));
As it's exclusive max `>=` is ok, Added inclusive min, as 0 is used when user is prompt to choose an entry.

2022-01-04 07:57 UTC, guilgaly commented on src/main/java/io/gatling/plugin/EnterprisePluginClient.java
> +    }
`UnsupportedOperationException` here is weird - the operation itself is supported (unlike, e.g., calling a mutating method on a non-modifiable collection, which would throw an `UnsupportedOperationException`). IMO, this could be:
- an `IllegalStateException` if it's not something that should happen in normal usage (possibly OK for the first one).
- a checked exception extending `EnterpriseClientException` if it's something the end user should be aware of (especially in the case where there are several teams, with this change we can no longer easily catch the appropriate exception and show the user how to configure a team ID in their build tool's configuration style).

2022-01-04 13:02 UTC, merged