feat: parse system properties as string, closes MISC-388
gatling/gatling-enterprise-plugin-commons pull request #60
Opened 2022-05-30 06:57 UTC by ccedric

Motivation:
- multiple build plugins have trouble parsing system properties to a Map

Modification:
- add the option to pass system properties as an encoded string
- following format is used: key1=value1,key2=value2
- system properties encoded as a string overrides the system properties as map

2022-05-30 07:00 UTC, ccedric commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +  public static Map<String, String> getProperties(
I'm not sure if the string should overrides the map, or just merge with it.
The string will mainly be used in command line (for a specific run), whereas the map will be used in the config line (for the whole project).

2022-05-30 08:29 UTC, tpetillot requested changes

2022-05-30 08:59 UTC, ccedric commented on src/main/java/io/gatling/plugin/BatchEnterprisePluginClient.java
> +      Map<String, String> systemProperties,
I think we should keep as much logic as possible in the commons.
It includes the choice of overriding the map by the formatted string for example.
It does add more params to the public functions, but I think we don't really care as it is a private project.

2022-05-31 08:41 UTC, tpetillot commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +  }
Shouldn't that be defined on `Properties`? More over, what's the point to keep both in memory if only one will be consumed.

IMO, this utility class should be able to define properties from string, maybe if really needed (but it should be the responsability of build tools IMO) the override mechanism.

Properties should still be only a map.

2022-06-03 08:47 UTC, Isammoc commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
**blocking:** Potential issues:

```java

  @Test
  void parseProperties_WhitespacePropertyName() {
    String properties = "key1 name=value1,key2=value2";
    final Map<String, String> propertiesMap = new HashMap<>();
    propertiesMap.put("key2", "value2");
    assertEquals(propertiesMap, PropertiesParserUtil.parseProperties(properties));
  }

  @Test
  void parseProperties_escapedComma() {
    String properties = "key1=value1.1\\,value1.2,key2=value2";
    final Map<String, String> propertiesMap = new HashMap<>();
    propertiesMap.put("key1", "value1.1,value1.2");
    propertiesMap.put("key2", "value2");
    assertEquals(propertiesMap, PropertiesParserUtil.parseProperties(properties));
  }

  @Test
  void parseProperties_equalSignInContent() {
    String properties = "key1=v1=value1,key2=value2";
    final Map<String, String> propertiesMap = new HashMap<>();
    propertiesMap.put("key1", "v1=value1");
    propertiesMap.put("key2", "value2");
    assertEquals(propertiesMap, PropertiesParserUtil.parseProperties(properties));
  }
```

The last one can easily be done:

```suggestion
    return Arrays.stream(properties.split(","))
        .map(property -> property.split("=", 2))
        .filter(property -> property.length == 2)
        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
```

2022-06-03 08:54 UTC, slandelle commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
No need to try to be perfect on this. The usage is System props and env vars. We don't have to support any weird data psychos might come up with. If weird data doesn't work, so be it.

2022-06-03 08:55 UTC, slandelle approved these changes

2022-06-03 08:57 UTC, guilgaly approved these changes

2022-06-03 08:58 UTC, Isammoc commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
1. It's not weird to have a `=` or `,` in a wanted value for the simulation
2. whitespace in property name or in environment variable name can be a source of security issue.
(name="echo 'PWN'; REAL_ENV")

We might execute any arbitrary command before launching the run.

2022-06-03 08:59 UTC, slandelle commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
I'd say to throw an exception if there's a whitespace in the key.

2022-06-03 09:09 UTC, Isammoc commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
So, quick wins:
* Add the `, 2` for split limit (to allow `=` in value)
* Throw an exception if there's whitespace

The escape of the comma `,` can be cumbersome to overcome

:ok_hand:

2022-06-03 09:16 UTC, slandelle commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +        .collect(Collectors.toMap(property -> property[0].trim(), property -> property[1].trim()));
Fine with me. @ccedric could you please change accordingly?

2022-06-03 09:16 UTC, notdryft commented
There a some typos to fix in the commit message

2022-06-03 09:17 UTC, notdryft commented
> feat: Parse sytem
> feat: Parse sy**s**tem

> added a PropertiesParserUtil which parse
> added a PropertiesParserUtil which parse**s**

2022-06-03 11:48 UTC, Isammoc commented on src/main/java/io/gatling/plugin/util/PropertiesParserUtil.java
> +                  if (key.contains(" ")) {
Space is not the only problematic character

```suggestion
                  if (key.matches(".*\\s.*")) {
```

Note: `\\s` will match ANY whitespace character from UTF-8

2022-06-03 12:21 UTC, bastien-gatling approved these changes

2022-06-03 12:43 UTC, Isammoc approved these changes

2022-06-03 13:31 UTC, merged