Add ability to monitor progress and wait for run end for enterpriseStart
gatling/gatling-enterprise-plugin-commons pull request #85
Opened 2023-01-25 07:59 UTC by guilgaly

2023-02-01 08:38 UTC, Isammoc commented on src/main/java/io/gatling/plugin/PluginClient.java
> +        throw (EnterprisePluginException) e1;
1. rethrow a catched exception is a bad practice
2. no need to cast it

2023-02-01 08:38 UTC, Isammoc commented on src/main/java/io/gatling/plugin/PluginClient.java
> +    }
weird to log multiple time.

Please log only one time (perhaps with formatted string)

2023-02-01 08:38 UTC, Isammoc commented on src/main/java/io/gatling/plugin/PluginClient.java
> +  }
same

2023-02-01 08:38 UTC, Isammoc commented on src/main/java/io/gatling/plugin/RunStatusTask.java
> +                errorCount, e.getMessage()));
Is it on purpose that you don't show the stacktrace?

2023-02-01 08:38 UTC, Isammoc commented on src/main/java/io/gatling/plugin/RunStatusTask.java
> +    logMetricsSummary(metricsSummary);
Inline?

2023-02-01 08:38 UTC, Isammoc commented on src/main/java/io/gatling/plugin/client/http/RunsApiRequests.java
> +            throw new RunNotFoundException(runId);
A throw in a lambda?

2023-02-01 09:46 UTC, tpetillot commented on src/main/java/io/gatling/plugin/RunStatusTask.java
> +  private void logMetricsSummary(MetricsSummary summary) {
nit: I would have separate metrics logging output mechanism and formatting to dedicated classes.

2023-02-01 10:51 UTC, guilgaly commented on src/main/java/io/gatling/plugin/RunStatusTask.java
> +  }
(Based on **it**, not him. 😉)

-----

Retry is handled by :
```
if (errorCount < 5) {
  // just log the error, so we'll keep executing every 5 seconds
} else {
  // call setException(), which stores the exception and cancels the execution
}
```

2023-02-01 11:16 UTC, tpetillot commented on src/main/java/io/gatling/plugin/RunStatusTask.java
> +  }
Oh right, the TimerTask doesn't retry on exception, thanks!

2023-02-02 10:25 UTC, guilgaly commented on src/main/java/io/gatling/plugin/PluginClient.java
> +    }
With a single log statement, I can't have different log levels for successes and errors. E.g., in Maven, this:

![Capture d’écran 2023-02-01 à 17 50 44](https://user-images.githubusercontent.com/6560742/216111055-66bd2962-3a41-4dfa-92fc-f8010049e8b6.png)

compared to this:

![Capture d’écran 2023-02-01 à 17 55 39](https://user-images.githubusercontent.com/6560742/216111155-0e11b855-195d-42e2-9cf9-aadeb0a37b67.png)

I could also format the result myself, I got to something like this:

![Capture d’écran 2023-02-02 à 10 58 16](https://user-images.githubusercontent.com/6560742/216293394-116eba03-b9ad-46b1-8451-efd1b866333e.png)

But then I also need to get into how color output gets enabled/disabled in each build tool (e.g. Maven with either the `--batch-mode` option or the `style.color` env var, etc.)... Which probably isn't worth it right now.

2023-02-02 10:26 UTC, guilgaly commented on src/main/java/io/gatling/plugin/PluginClient.java
> +    }
In the end, here's what I have (in Maven) with some minor clean ups only:

![Capture d’écran 2023-02-02 à 11 25 21](https://user-images.githubusercontent.com/6560742/216299515-0fd4080f-054f-4ac4-af1c-4bcd9cdc3f89.png)

Not great, not terrible. 🤷‍♂️ Suggestions are welcome, but I've already spent way to much time on this...

2023-02-02 10:34 UTC, slandelle commented on src/main/java/io/gatling/plugin/PluginClient.java
> +        throw (EnterprisePluginException) e1;
> rethrow a catched exception is a bad practice

Personally, I don't care :)

2023-02-02 10:50 UTC, guilgaly commented on src/main/java/io/gatling/plugin/PluginClient.java
> +        throw (EnterprisePluginException) e1;
To be fair, the way I handled exceptions was a bit more complicated than it needed to be. Changed that in the fixup I just pushed.

2023-02-02 10:53 UTC, guilgaly commented on src/main/java/io/gatling/plugin/PluginClient.java
> +        throw (EnterprisePluginException) e1;
(Regarding 2.: the cast was required because you can't throw an `Exception` in a method which only declares throwing `EnterprisePluginException`, and the `instanceof` check doesn't implicitly change the type of `e1` in Java. Anyway, this is simplified now.)

2023-02-02 10:56 UTC, guilgaly commented on src/main/java/io/gatling/plugin/client/http/RunsApiRequests.java
> +            throw new RunNotFoundException(runId);
Sure, why not? The functional interface expected by `getJson` for this parameter declares that the function may throw an `EnterprisePluginException`.

2023-02-02 13:05 UTC, Isammoc commented on src/main/java/io/gatling/plugin/PluginClient.java
> +        throw (EnterprisePluginException) e1;
```suggestion
  catch (EnterprisePluginException e) {
    throw e;
  } catch (Exception other) {
    throw new EnterprisePluginException("", e);
  }
```

2023-02-02 13:06 UTC, Isammoc commented on src/main/java/io/gatling/plugin/client/http/RunsApiRequests.java
> +            throw new RunNotFoundException(runId);
oh! ok (was used to use Runnable interface... )

2023-02-02 13:31 UTC, guilgaly commented on src/main/java/io/gatling/plugin/RunStatusTask.java
> +  private void logMetricsSummary(MetricsSummary summary) {
it's not going to be used elsewhere, so I'd say it's fine like this for now?

2023-02-03 12:48 UTC, Isammoc approved these changes

2023-02-03 13:55 UTC, notdryft commented on src/main/java/io/gatling/plugin/model/RunStatus.java
> +  KillRequested(15, true, false);
Did we change the naming in Cloud?
In SH, 15 is StopRequested, 14 is unused (so no case object at all), 13 is InsufficientLicense (very different term from invalid), 7 is just Stopped and so on.

2023-02-03 13:57 UTC, notdryft commented on src/main/java/io/gatling/plugin/model/RunStatus.java
> +  KillRequested(15, true, false);
Actually 13 is InsufficientCredit in Cloud, InsufficientLicense SH.

2023-02-03 14:00 UTC, notdryft requested changes

2023-02-03 14:00 UTC, notdryft commented on src/main/java/io/gatling/plugin/model/RunStatus.java
> +  KillRequested(15, true, false);
As this is only meant for enterpriseStart, I guess it should align with Cloud naming.

2023-02-03 15:50 UTC, guilgaly commented on src/main/java/io/gatling/plugin/model/RunStatus.java
> +  KillRequested(15, true, false);
For some reason, I based this on the CI plugins' code... Differences:

|    | self-hosted             | cloud                   | CI plugins      |
|----|-------------------------|-------------------------|-----------------|
| 13 | InsufficientLicense     | InsufficientCredit      | INVALID_LICENSE |
| 14 | (unused, was Collected) | (unused, was Collected) | COLLECTED       |
| 15 | StopRequested           | StopRequested           | KILL_REQUESTED  |

1. I'll use `InsufficientCredit` here for 13. For the CI plugins, should it be something like `InsufficientCreditOrLicense`? Bit of a kludge...
2. According to the git history for self-hosted, 14/`Collected` was removed in 2018. That's ancient history, I think we can remove it from the plugins. ^^
3. I'll rename `KillRequested` to `StopRequested` ☮️

2023-02-03 16:13 UTC, guilgaly commented on src/main/java/io/gatling/plugin/model/RunStatus.java
> +  KillRequested(15, true, false);
I've changed these here.

2023-02-06 16:11 UTC, notdryft commented on src/main/java/io/gatling/plugin/model/RunStatus.java
> +  KillRequested(15, true, false);
Created an issue for alignment: https://gatlingcorp.atlassian.net/browse/MISC-430

2023-02-06 16:11 UTC, notdryft approved these changes

2023-02-08 08:40 UTC, merged